version: "3.9"

services:
  db:
    container_name: schemaBasedTenancy-db
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: hrm-main-db
      POSTGRES_USER: hrmuser
      POSTGRES_PASSWORD: hrmpassword
    ports:
      - 5434:5434
    volumes:
      - ./docker/pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
      # target: development
    image: schema-tenancy-api:dev
    command: yarn run start:dev
    container_name: schema-tenancy-test-api
    restart: unless-stopped
    volumes:
      - /app/node_modules
      - .:/app
    ports:
      - 9000:9000
    environment:
      CHOKIDAR_USEPOLLING: "true"
    # env_file: .env
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4
    container_name: schema-tenancy-db-admin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 5060:80
